.TH UUID_CATEGDIR

.SH NAME
uuid_categDir \- generate UUIDs and categorise content in each directory.

.SH SYNOPSIS
.B uuid_categDir
[\fB\-n\fR \ OPTIONS\fR] [\fB\-DIRECTORY\fR]
[\fIdirectory ...\fR]
[\fB\-l \fIlogfile\fR] [\fI\-\-logfile=\fIlogfile\fR]
[\fB\-p\fR] [\fI\-\-print\fR]

.SH DESCRIPTION
 \fBuuid_categDir\fR script performs various operations including generating UUIDs, categorising content in directories and logging user logins and commands.
It performs the following tasks:

- Generates UUIDs
- Navigates to each child directory and counts the number of files of each type.
- Calculates the total space used by the files in each child directory.
- Identifies the shortest and longest filenames in each child directory.
- Logs user login and script commands.
- Outputs the analysis results for each child directory.



.SH OPTIONS
.TP
.B \-3, \-\-generate-uuid-v3
Generate UUID version 3.

.TP
.B \-5, \-\-generate-uuid-v5
Generate UUID version 5.

.TP
.B \-l \fIlogfile\fR, \-\-logfile=\fIlogfile\fR
Specify the log file to save the output.

.TP
.B \-p, \-\-print
Print the output without saving to a log file.

.TP
.B \-d, \-\-\directory 
Specify the directory where the script operates.

.SH AUTHOR
Written by Ramona Ciceu.


.SH REPORTING BUGS
Report bugs to: ramona@canterbury.ac.uk
